### PR TITLE
#29: replace setTimeout and requestAnimationFrame with d3-timer

### PR DESCRIPTION
**Pull request by guykr**
Here is a first stab at this.

I wasn't sure what to do with the velocity value, as d3-timer has different semantics, so I opted to preserve the performance of the current implementation by calculating a `VELOCITY_MULTIPLIER` so that the end result is the same.

Please ignore the build products, but as they are already in git I am submitting them as well.

### CODE REVIEW

**Comment by exogen** [comment]
@guykr-stratoscale Like the idea! I think we should ditch `velocity` and migrate to `duration` anyway, as that's how every other animation lib works and it makes coordinating multiple animations easier. See issue #21.

Aside from that, I think we should land this PR soon, but could someone take a look at #23 so we can merge that first? Then the `d3-timer` code here will be simplified too, as opposed to keeping the duplication around.

/cc @boygirl @kenwheeler

**Comment by boygirl** [comment]
@guykr-stratoscale

We're doing a release tomorrow, and I would really like this code to be part of it. Do you have a minute to resolve the merge conflicts (my fault, sorry!) and remove all of the `dist` files from this PR?

Thanks!

**Comment by guykr** [comment]
@boygirl 
Sorry, I spend some time now trying to merge the conflicts, but as the code changed quite a lot I don't have the time to complete it by tomorrow.

**Comment by boygirl** [comment]
@guykr-stratoscale sorry about that. We will probably create a new branch for this work so we can get it in for this release, but I'll be sure to credit you in the commit / release notes.

**Comment by boygirl** [comment]
@guykr-stratoscale a branch based on your work was pushed to master with a commit crediting you by name / gh-handle 

https://github.com/FormidableLabs/victory-animation/pull/34

**Pull request closed without merging**
